### ISSUE TITLE
Add a Config file for at least the spawn weight.

### ISSUE THREAD

**Issue by fbottarelli** [AquUpd/CaracalMob#11]
I really like this mobs but for my personal taste the spawn rate is really high, In any savanas. Even if the area is small, there are many,

I don't know how much is difficult to add a configurable file for user but i think is something necessary in any mobs mod at least for adjust the spawn rate. 

Anyway thanks for the cool mod!

**Comment by Ivan-Khar** [comment]
Hello! There's already config file located in ./config/AqMods/caracal.config

**Comment by Ivan-Khar** [comment]
In there you can modify these values to modify spawn weights and etc:
spawn.max=4
spawn.weight=50
spawn.min=2
