### ISSUE TITLE
Crash Report [CaracalEntity$SleepWithOwnerGoal.dropMorningGifts]

### ISSUE THREAD

**Issue by Chill907Gaming** [AquUpd/CaracalMob#13]
**Describe the bug**
The crash happened 1 minute and 1 second after my friend teleported home, not sure if that is related but I figured he was probably far away and although all the tamed caracals are in the spawn chunks and should stay loaded, I feel that him teleporting loaded something that took a minute to crash the server. When he was done adventuring or something he teleported home and 1 minute later there was a ticking entity error. I know those are usually impossible to identify the cause but I figured it was worth sending in the crash. 

The server has been up for over 2 days and typically I restart it every 2 days so no harm done.

**To Reproduce**
I have only experienced this once as far as I know but if I find a way to reproduce it I will tell you.

We teleport home very often with no problems but maybe just the timing of teleporting home mixed with the caracal giving presents borked it up. Also **all of the caracals are sitting** so none of them should be giving gifts, right?

here is my latest.log
[latest.log](https://github.com/AquUpd/CaracalMob/files/8926249/latest.log)
and my crash report
[crash-2022-06-16_15.00.46-server.txt](https://github.com/AquUpd/CaracalMob/files/8926277/crash-2022-06-16_15.00.46-server.txt)

**Friends and my own Desktops are identical:**
 - OS: Windows 10
 - Minecraft 1.19
 - Fabric mod loader version 0.14.7
 - Mod version caracal-1.19-1.3.8
 
 **Server:**
 - OS: Docker
 - Minecraft 1.19
 - Fabric mod loader version 0.14.7
 - Mod version caracal-1.19-1.3.8

**Comment by Ivan-Khar** [comment]
I'll look into that

**Comment by Ivan-Khar** [comment]
Yeah, fixed in the latest version
https://github.com/AquUpd/CaracalMob/releases/tag/1.19-1.3.9
