### ISSUE TITLE
Caracal issues with Capybara mod (Fabric)

### ISSUE THREAD

**Issue by Monikaahh** [AquUpd/CaracalMob#14]
On my Minecraft server, we have installed this lovely mod as well as the Capybara mod for Fabric. But when the Caracal and the Capybara are nearby, the Caracal seems to slide over onto the Capybara no matter what - even when on a leash or sitting- and causes the Capybara to forever be walking, which can be annoying because it just walks and teleports to me. (I hope I worded that right.)
I also posted this on the issues tab for the Capybara mod and I'm hoping this issue can be fixed so they can work together!

1. Summon a tamed Caracal and a tamed Capybara
2. Let them be at least 5 blocks nearby, and have the Caracal sit
3. Sit back and observe the Caracal

I expect the Caracal to just seemingly slide over to the Capybara and sit on top of it.

A few screenshots to show what I mean:
(https://user-images.githubusercontent.com/107805586/174489729-dc6c8f71-2757-4918-a2e8-0ca88c3aa20f.png)
Now while this can be a cute feature, it can be annoying because I'll be mining and since the Capybara is stuck walking both of the mods will teleport to me and risk death.

 - OS: Windows 10
 - Browser: Google Chrome 
 - Version: 21H2

**Comment by Ivan-Khar** [comment]
Okay, I'll look into that

**Comment by Ivan-Khar** [comment]
Okay, at first caracals(and other entities) riding capybaras is a feature of capybara mod
https://github.com/ZestyBlaze/Capybara-Fabricated/issues/7
But I'll look what I can do in order to make caracals sit in place when they near capybaras

**Comment by Ivan-Khar** [comment]
I will close this issue because this bug is not from my side. 
https://github.com/ZestyBlaze/Capybara-Fabricated/issues/10
