### ISSUE TITLE
Fabric 1.19

### ISSUE THREAD

**Issue by sadlyborger** [AquUpd/CaracalMob#16]
I got an error when I play with the recent update on 1.19.
I have to install fabric api version 0.58.0+1.19 even when its already installed in my mods folder.

**To Reproduce**
1. Go to 'Minecraft Launcher and run fabric 1.19 with fabric api version 0.58.0+1.19 included the mod Caracal'
2. Click on 'Start Game'
3. See error

**Logs**
Log file or logs pasted on pastebin
https://pastebin.com/BirLF57u

![image](https://user-images.githubusercontent.com/108927538/186995336-d5fc0a1a-ad51-419e-9997-a4c961a1d227.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2
 - Modloader Fabric 0.14.9

**Comment by Ivan-Khar** [comment]
Mhm, Gonna fix that in a moment

**Comment by Ivan-Khar** [comment]
Oh yeah, 1.19 Fabric API id was "fabric" and not "fabric-api". Gonna be fixed in 1.19-2.0.2.1

**Comment by Ivan-Khar** [comment]
Should be fixed

**Comment by sadlyborger** [comment]
Thank you very much.
