### ISSUE TITLE
[1.19.30 CTD Spawning Caracal

### ISSUE THREAD

**Issue by Dragonfly-Totem** [AquUpd/CaracalMob#17]
**System**
Minecraft 1.19.3
Fabric Launcher 1.14.14
Fabric API 0.75.1
Caracal 2.1.0
GeckoLib 4.0.4

**Bug**: Crash to desktop when rendering caracals in world
**Error**:
The game crashed whilst rendering entity in world
Error: java.lang.AbstractMethodError: Receiver class com.aqupd.caracal.entity.CaracalEntity does not define or inherit an implementation of the resolved method 'abstract void registerControllers(software.bernie.geckolib.core.animation.AnimatableManager$ControllerRegistrar)' of interface software.bernie.geckolib.core.animatable.GeoAnimatable.

**Replication**: Simply spawn a caracal with a spawn egg.
**Expected behavior**: Caracal should appear and crash my brain with its floppa adorableness.

**Comment by ColinVaughn** [comment]
revert back to GeckoLib 4.0.0 they removed software.bernie.geckolib.core.animation.AnimationEvent

**Comment by Ivan-Khar** [comment]
Yea it's probably something with new versions of geckolib. Gonna fix it in a moment, thanks for reporting!

**Comment by Ivan-Khar** [comment]
Fixed in 2.1.1!
