### ISSUE TITLE
Caracals not dancing [1.19.2 FORGE]

### ISSUE THREAD

**Issue by MagmaForce3400** [AquUpd/CaracalMob#18]
**Describe the bug**
Tamed caracals aren't dancing when they are near a jukebox

**To Reproduce**
1. Tame a caracal
2. Make it sit, or not, doesn't matter
3. Place a jukebox next to it, under it whatever as long as it is near the caracal
4. Put a music disc inside it
5. See that the caracal isn't dancing

**Expected behavior**
The caracal dances with some sick beats

**Comment by Ivan-Khar** [comment]
Forge version doesn't have this feature

**Comment by Ivan-Khar** [comment]
Oh, yeah, forgot to mention. I will port current fabric version to forge, but it will take some time
