### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by JedaiGames** [AquUpd/CaracalMob#19]
**Describe the bug**
Game crashing on launch with mod

**To Reproduce**
1. Setup Fabric
2. Download caracal mod
3. Launch game
4. Die (game crashed because yes)

**Expected behavior**

**Logs**
[message.txt](https://github.com/Ivan-Khar/CaracalMob/files/13190884/message.txt)

**Screenshots**
![изображение_2023-10-27_183928204](https://github.com/Ivan-Khar/CaracalMob/assets/63721354/f67d2d39-b976-42d5-9513-7873d722b696)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Caracal mod 2.0.2
 - Modloader Fabric 0.14.22

**Comment by JedaiGames** [comment]
Ah, yes. Version of game is Minecraft 1.19.2

**Comment by Ivan-Khar** [comment]
Попробуй конфиг удалить или в файл ./config/AqMods/caracal.config написать:
```
config.version=1
spawn.max=4
spawn.biomes=Doesn't work
entity.speed=0.3
spawn.weight=50
entity.knockback=0.5
spawn.min=2
entity.health=10.0
entity.damage=2.5
entity.follow=20.0
```

**Comment by JedaiGames** [comment]
Конфигов и не было, с нуля устанавливал на чистый майн. 
А насчёт замены посмотрим.

**Comment by Ivan-Khar** [comment]
Stale issue
