### ISSUE TITLE
Вылет

### ISSUE THREAD

**Issue by DisaKzionda** [AquUpd/CaracalMob#5]
![image](https://user-images.githubusercontent.com/53359732/120069006-f451ef00-c0c6-11eb-9415-410006fa9956.png)
Я играл и путешествовал по миру с флопой но сервер перестал работать с этим модом что у меня что у друга после перезапуска сервера

**Comment by DisaKzionda** [comment]
![2021-05-29_21 13 03](https://user-images.githubusercontent.com/53359732/120069164-cae59300-c0c7-11eb-8bdb-0d3322929339.png)
За что где мой флопа

**Comment by AquUpd** [comment]
В версии 1.0.4 исправлено, скоро опубликую

**Comment by DisaKzionda** [comment]
Понял

**Comment by AquUpd** [comment]
> Понял

https://github.com/AquUpd/CaracalMob/releases/tag/1.0.4
