### ISSUE TITLE
Why are you jij so many fabric api modules?

### ISSUE THREAD

**Issue by K0-RR** [AquUpd/CaracalMob#6]
Jar-in-jaring fabric modules is good but only when you need two or three of them. Your mod requires 10 so wouldn't it be better to just make it require fabric api in the fabric.mod.json file? Nearly all mods require a whole fabric API mod so all these modules you need are already in the mods folder of the users.
This way you will cut by 1/3 the size of your mod.
Thanks for this mod of course.

**Comment by Ivan-Khar** [comment]
Why not? It's literally 400kb+- because of built in Fabric API modules.
