### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by GDBrallon** [AquUpd/CaracalMob#9]
Crash log
[crash-2021-12-05_15.54.54-client.txt](https://github.com/AquUpd/CaracalMob/files/7656897/crash-2021-12-05_15.54.54-client.txt)
No other mods added

**Comment by GDBrallon** [comment]
this is happening with other mods, so its not this mods fault.

**Comment by Ivan-Khar** [comment]
Can you provide latest.log after crash?

**Comment by Ivan-Khar** [comment]
Closing Issue
